# Generated by Django 4.0.4 on 2022-10-02 21:21

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('order_product', models.CharField(max_length=100)),
                ('order_product_id', models.CharField(max_length=50)),
                ('order_product_price', models.IntegerField()),
                ('order_product_quantity', models.CharField(max_length=100)),
                ('order_product_color', models.CharField(max_length=50)),
                ('order_product_size', models.CharField(max_length=20)),
                ('order_product_value', models.CharField(max_length=100)),
                ('order_product_image', models.ImageField(blank=True, upload_to='products/')),
            ],
            options={
                'verbose_name_plural': 'All orders',
                'db_table': 'ecommerce_all_orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('order_product', models.CharField(max_length=100)),
                ('order_product_id', models.CharField(max_length=100)),
                ('order_product_quantity', models.CharField(max_length=100)),
                ('order_product_color', models.CharField(max_length=50)),
                ('order_product_price', models.IntegerField()),
                ('order_product_size', models.CharField(max_length=20)),
                ('order_product_value', models.CharField(max_length=100)),
                ('order_product_image', models.ImageField(blank=True, upload_to='products/')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'ecommerce_cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.PositiveIntegerField()),
                ('blue', models.PositiveIntegerField()),
                ('green', models.PositiveIntegerField()),
                ('black', models.PositiveIntegerField()),
                ('orange', models.PositiveIntegerField()),
                ('yellow', models.PositiveIntegerField()),
                ('white', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentLookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('lookbook_image', models.ImageField(blank=True, upload_to='products/')),
                ('product_category', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ecommerce_current_session',
            },
        ),
        migrations.CreateModel(
            name='LocalStores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('map_url', models.URLField(default=None, null=True)),
                ('about_store', models.TextField(max_length=500)),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('marketing_director', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(default=None, max_length=50)),
                ('web_address', models.URLField(default=None, max_length=30)),
                ('e_mail', models.EmailField(blank=True, max_length=254)),
                ('facebook_link', models.URLField(blank=True, max_length=100, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=100, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=100, null=True)),
                ('pinterest_link', models.URLField(blank=True, max_length=100, null=True)),
                ('weekdays_working_hours', models.CharField(default=None, max_length=20)),
                ('saturday_working_hours', models.CharField(default=None, max_length=20)),
                ('sunday_working_hours', models.CharField(default=None, max_length=20)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Store',
                'db_table': 'ecommerce_store',
            },
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('password2', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('surname', models.CharField(max_length=50, null=True)),
                ('addres', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'New user',
                'verbose_name_plural': 'New users',
                'db_table': 'ecommerce_newuser',
            },
        ),
        migrations.CreateModel(
            name='OrderValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('products', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('card_number', models.BigIntegerField()),
                ('expiration_date', models.CharField(max_length=50)),
                ('security_code', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Order values',
                'db_table': 'ecommerce_order_values',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(max_length=3)),
                ('blue', models.CharField(max_length=4)),
                ('green', models.CharField(max_length=5)),
                ('black', models.CharField(max_length=5)),
                ('orange', models.CharField(max_length=6)),
                ('yellow', models.CharField(max_length=6)),
                ('white', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Colour',
                'verbose_name_plural': 'Colours',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xxs', models.PositiveIntegerField()),
                ('xs', models.PositiveIntegerField()),
                ('s', models.PositiveIntegerField()),
                ('m', models.PositiveIntegerField()),
                ('l', models.PositiveIntegerField()),
                ('xl', models.PositiveIntegerField()),
                ('xxl', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('session_started', models.CharField(max_length=20)),
                ('session_started_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ecommerce_user_session',
            },
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default=None, max_length=30)),
                ('model', models.CharField(default=None, max_length=30)),
                ('NO_of_availabile_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.color')),
                ('NO_of_availabile_sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.productsize')),
            ],
        ),
        migrations.CreateModel(
            name='Jeans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default=None, max_length=30)),
                ('model', models.CharField(default=None, max_length=30)),
                ('color', models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('white', 'White')], max_length=15, null=True)),
                ('width', models.CharField(choices=[('skinny', 'Skinny'), ('slim', 'Slim'), ('regular', 'Regular'), ('wide', 'Wide')], max_length=15)),
                ('height', models.CharField(choices=[('Mens', (('xxs', 'UK 26; Europe 42; USA 26; International XXS'), ('xs', 'UK 28; Europe 44; USA 28; International XS'), ('s', 'UK 30; Europe 46; USA 30; International S'), ('m', 'UK 32; Europe 48; USA 32; International M'), ('l', 'UK 34; Europe 50; USA 34; International L'), ('xl', 'UK 36; Europe 52; USA 36; International XL'), ('xxl', 'UK 38; Europe 54; USA 38; International XXL'), ('xxxl', 'UK 40; Europe 56; USA 40; International XXL'))), ('Women', (('xxs', 'UK 24; Europe 40; USA 24; International XXS'), ('xs', 'UK 26; Europe 42; USA 26; International XS'), ('s', 'UK 38; Europe 44; USA 38; International S'), ('m', 'UK 30; Europe 46; USA 30; International M'), ('l', 'UK 32; Europe 48; USA 32; International L'), ('xl', 'UK 34; Europe 50; USA 34; International XL'), ('xxl', 'UK 36; Europe 52; USA 36; International XXL'), ('xxxl', 'UK 38; Europe 54; USA 38; International XXL'))), ('Child', (('1 - 12 months', '1 - 12 months'), ('1 - 2 years', '1 - 2 years'), ('2 - 3 years', '2 - 3 years'), ('3 - 4 years', '3 - 4 years'), ('4 - 5 years', '4 - 5 years'), ('5 - 6 years', '5 - 6 years'), ('6 - 7 years', '6 - 7 years'), ('7 - 8 years', '7 - 8 years'), ('8 - 9 years', '8 - 9 years'), ('9 - 10 years', '9 - 10 years'), ('10 - 11 years', '10 - 11 years'), ('11 - 12 years', '11 - 12 years'), ('12 - 13 years', '12 - 13 years'), ('13 - 14 years', '13 - 14 years'))), ('unknown', 'Unknown')], max_length=15)),
                ('NO_of_availabile_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.color')),
                ('NO_of_availabile_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.productsize')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(db_index=True, max_length=100)),
                ('short_product_description', models.CharField(max_length=150)),
                ('long_product_description', models.TextField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('white', 'White')], max_length=10)),
                ('status', models.CharField(choices=[('on_count', 'On count'), ('off_count', 'Off count')], default='off_count', max_length=10)),
                ('category', models.CharField(blank=True, choices=[('hats', 'Hats'), ('shirts', 'Shirts'), ('jeans', 'Jeans'), ('shoes', 'Shoes')], max_length=10)),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.productsize')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'ecommerce_product',
                'ordering': ('product_title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
