# Generated by Django 4.0.4 on 2022-08-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentLookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('lookbook_image', models.ImageField(blank=True, upload_to='products/')),
                ('product_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('hats', 'Hats'), ('shirts', 'Shirts'), ('jeans', 'Jeans'), ('shoes', 'Shoes')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='ecommerce_cart',
        ),
    ]
