# Generated by Django 4.0.4 on 2022-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_currentlookbook_test_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('about_store', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Store',
                'db_table': 'ecommerce_store',
            },
        ),
    ]
