# Generated by Django 4.0.4 on 2022-08-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='LocalStores',
        ),
    ]
