# Generated by Django 4.0.4 on 2022-08-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_rename_store_localstores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localstores',
            old_name='street',
            new_name='address',
        ),
        migrations.AddField(
            model_name='localstores',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='localstores',
            name='phone_number',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='localstores',
            name='saturday_working_hours',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='localstores',
            name='sunday_working_hours',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='localstores',
            name='weekdays_working_hours',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
