# Generated by Django 4.0.4 on 2022-08-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_rename_street_localstores_address_localstores_e_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localstores',
            name='web_address',
            field=models.URLField(default=None, max_length=30),
        ),
    ]
