# Generated by Django 4.0.4 on 2022-08-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_localstores_web_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='localstores',
            name='facebook_link',
            field=models.URLField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='localstores',
            name='instagram_link',
            field=models.URLField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='localstores',
            name='pinterest_link',
            field=models.URLField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='localstores',
            name='twitter_link',
            field=models.URLField(default=None, max_length=100),
        ),
    ]
