# Generated by Django 4.0.4 on 2022-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_localstores_facebook_link_localstores_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localstores',
            name='facebook_link',
            field=models.URLField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localstores',
            name='instagram_link',
            field=models.URLField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localstores',
            name='pinterest_link',
            field=models.URLField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localstores',
            name='twitter_link',
            field=models.URLField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
