# Generated by Django 4.0.4 on 2022-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_alter_localstores_facebook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_director', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'Customers support',
                'verbose_name_plural': 'Customers supports',
                'db_table': 'ecommerce_CustomersSupport',
            },
        ),
    ]
