# Generated by Django 4.0.4 on 2022-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_customerssupport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomersSupport',
        ),
        migrations.AddField(
            model_name='localstores',
            name='director',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='localstores',
            name='marketing_director',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
