# Generated by Django 4.0.4 on 2022-09-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_delete_customerssupport_localstores_director_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
