# Generated by Django 4.0.4 on 2022-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0013_alter_newuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ecommerce_current_session',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('session_started', models.CharField(max_length=20)),
                ('session_started_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ecommerce_user_session',
            },
        ),
        migrations.AddField(
            model_name='localstores',
            name='map_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
