# Generated by Django 4.0.4 on 2022-09-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0014_currentsession_usersession_localstores_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localstores',
            name='map_url',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
