# Generated by Django 4.0.4 on 2022-09-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0015_alter_localstores_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localstores',
            name='map_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
